# NUMPY: Is a Data science package that are used for numerical analysis and it's more popular and faster.

 Import the numpy package under the name np

In [1]:
# mporting the numpy Library
import numpy as np

Print the numpy version and the configuration

In [2]:
# Print NumPy version
print("NumPy version:", np.__version__)

# Print NumPy configuration
print("NumPy configuration:")
print(np.show_config())


NumPy version: 1.23.5
NumPy configuration:
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language =

Create a null vector of size 10

In [3]:
# Create a null vector of size 10
null_vector = np.zeros(10)

# Print the null vector
print("Null vector of size 10:", null_vector)


Null vector of size 10: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. # How to find the memory size of any array

In [4]:
# Create an array
arr = np.zeros((5, 8))  # Example array, replace with your array

# Find the memory size of the array
memory_size = arr.nbytes

# Print the memory size
print("Memory size of the array:", memory_size, "bytes")


Memory size of the array: 320 bytes


5. How to get the documentation of the numpy add function from the command line?

In [5]:
# write the following command in command prompt: python -m pydoc numpy.add


6. Create a null vector of size 10 but the fifth value which is 1

In [6]:
# Create a null vector of size 10
null_vector = np.zeros(10)

# Set the fifth value to 1
null_vector[4] = 1

# Print the null vector
print("Null vector of size 10 with the fifth value set to 1:", null_vector)


Null vector of size 10 with the fifth value set to 1: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49

In [7]:
# Create a vector with values ranging from 10 to 49
vector = np.arange(10, 50)

# Print the vector
print("Vector with values ranging from 10 to 49:", vector)


Vector with values ranging from 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last)

In [8]:
# Create a sample vector
new_vector = np.array([1, 2, 3, 4, 5])

# Reverse the vector
reversed_vector = new_vector[::-1]

# Print the reversed vector
print("Reversed vector:", reversed_vector)


Reversed vector: [5 4 3 2 1]


9. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
# Create a vector with values ranging from 0 to 8
vector2 = np.arange(9)

# Reshape the vector into a 3x3 matrix
matrix = vector2.reshape(3, 3)

# Print the matrix
print("3x3 matrix with values ranging from 0 to 8:")
print(matrix)


3x3 matrix with values ranging from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [10]:
# Find indices of non-zero elements from [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
print("Indices of non-zero elements:", non_zero_indices)

Indices of non-zero elements: (array([0, 1, 4]),)


11. Create a 3x3 identity matrix

In [11]:
# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:")
print(identity_matrix)

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Create a 3x3x3 array with random values

In [12]:
# Create a 3x3x3 array with random values
my_random_3d_array = np.random.rand(3, 3, 3)
print("3x3x3 Array with Random Values:")
print(my_random_3d_array)

3x3x3 Array with Random Values:
[[[0.64156609 0.15028774 0.42191824]
  [0.3006567  0.78525258 0.06074671]
  [0.78460937 0.59745548 0.6158533 ]]

 [[0.87088793 0.60247088 0.22097648]
  [0.0852487  0.57607374 0.51201091]
  [0.74413545 0.63842744 0.07607823]]

 [[0.65122329 0.02252001 0.63258551]
  [0.78454226 0.07529833 0.4552876 ]
  [0.55031554 0.14260783 0.40917242]]]


13. Create a 10x10 array with random values and find the minimum and maximum values

In [13]:
# Create a 10x10 array with random values and find the minimum and maximum values
random_10x10_array = np.random.rand(10, 10)
min_value = np.min(random_10x10_array)
max_value = np.max(random_10x10_array)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

Minimum Value: 0.001666556113376183
Maximum Value: 0.9915251361684424


14. Create a random vector of size 30 and find the mean value

In [14]:
# Create a random vector of size 30 and find the mean value
random_vector = np.random.rand(30)
mean_value = np.mean(random_vector)
print("Mean Value:", mean_value)

Mean Value: 0.5095849386111194


15. Create a 2d array with 1 on the border and 0 inside

In [15]:
# Create a 2d array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("2D Array with 1 on Border and 0 Inside:")
print(border_array)


2D Array with 1 on Border and 0 Inside:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array?

In [16]:
# 16. How to add a border (filled with 0's) around an existing array?
existing_array = np.ones((3, 3))
border_added_array = np.pad(existing_array, pad_width=1, mode='constant', constant_values=0)
print("Array with Border Added:")
print(border_added_array)

Array with Border Added:
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


17. Result of the following expressions

In [17]:
# 17. Result of the following expressions
print("Result of the following expressions:")
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

Result of the following expressions:
nan
False
False
nan
True
False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [18]:
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
diagonal_below_matrix = np.diag(1 + np.arange(4), k=-1)
print("5x5 Matrix with Values 1,2,3,4 Below the Diagonal:")
print(diagonal_below_matrix)

5x5 Matrix with Values 1,2,3,4 Below the Diagonal:
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [19]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern
checkerboard_matrix = np.zeros((8, 8), dtype=int)
checkerboard_matrix[1::2, ::2] = 1
checkerboard_matrix[::2, 1::2] = 1
print("8x8 Matrix with Checkerboard Pattern:")
print(checkerboard_matrix)

8x8 Matrix with Checkerboard Pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. Index (x,y,z) of the 100th element in a (6,7,8) shape array

In [20]:
# 20. Index (x,y,z) of the 100th element in a (6,7,8) shape array
array_shape = (6, 7, 8)
index_100th_element = np.unravel_index(100, array_shape)
print("Index of the 100th element in a (6,7,8) array:", index_100th_element)

Index of the 100th element in a (6,7,8) array: (1, 5, 4)
